---
name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install flatc
        run: |
          git clone https://github.com/google/flatbuffers.git
          pushd flatbuffers
          git checkout v22.9.29
          cmake .
          make -j flatc
          sudo mv flatc /usr/bin
          popd
          flatc --version

      - name: Install libhdf5
        run: |
          sudo apt update
          sudo apt install libhdf5-dev

      - name: Build schema wrapper library
        run: pushd streaming-types && cargo build && popd

      - name: rustfmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --no-deps -- -Dwarnings

      - name: Build and Test
        run: cargo test --all

  container-images:
    name: Build and push container image
    if: ${{ github.ref_type == 'tag' }}
    needs:
      - build-and-test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component:
          - events-to-histogram
          - frame-assembler
          - simulator
          - stream-to-file
          - trace-to-events

    steps:
      - uses: actions/checkout@v2

      - name: Build container image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: "supermusr-${{ matrix.component }}"
          tags: "latest ${{ github.ref_name }} ${{ github.sha }}"
          containerfiles: "./${{ matrix.component }}/Containerfile"
          oci: true

      - name: Push image to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/stfc-icd-research-and-design
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
